### ISSUE TITLE
HotmokaFE-SNAPSHOT-1.0.0

### ISSUE THREAD

**Issue by IsaccoSordo** [IsaccoSordo/hotmokaFE#6]
Gentile prof. Spoto,

ho terminato gli sviluppi aggiungendo anche la parte richesta del [tag.clazz](https://github.com/IsaccoSordo/hotmokaFE/commit/91bc5082b0cc2e2f350c5e7e7dbd03b2cdc1a82c#diff-adb4bb458c3a4adaf812fada6114c075503080d92a02a9a743a16736af8dc4fa).
Ho inoltre aggiornato il progetto all'ultimo commit  presente  (ad oggi 25/04) in master di [Hotmoka](https://github.com/Hotmoka/hotmoka).
Rimango a disposizione per aprire un branch  per poter aggiungere il progetto; in caso contrario Le chiedo cortesemente Sue indicazioni.

A breve La informerò sulla parte della tesi relativa alla presentazione.

Nel ringraziarLa per la disponibilità porgo cordiali saluti.

Isacco Sordo
VR422167

**Comment by IsaccoSordo** [comment]
Buonasera Professore,

ho modificato la visibilità del progetto, adesso è pubblico
Grazie.
Cordiali saluti

**Comment by spoto** [comment]
Perfetto grazie. Ho fatto il fork.
